models/ExpertTest.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "heart_disease_samples".
 *
 * @property int $id
 * @property int $age
 * @property string $chest_pain_type
 * @property int $rest_blood_pressure
 * @property string $blood_sugar
 * @property string|null $rest_electro
 * @property int $max_heart_rate
 * @property string $exercice_angina
 * @property string $disease
 */
class ExpertTest extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    //array:مصفوفة الأعداد المطلوب حساب الانحراف المعياري لها
    //mean:المتوسط الحسابي لعناصر المصفوفة
    static public function sd($array, $mean)
    {   
        foreach ($array as $index => $value) {
            $array[$index] = pow($value-$mean, 2);
        }
        return (array_sum($array)/(count($array)-1));
    }
    //val:القيمة المدخلة المراد حساب الكثافة من أجلها
    static public function density($array, $val)
    {
        $mean = (array_sum($array) / count($array));
        $sd = ExpertTest::sd($array, $mean);
        $d = (1/sqrt(2*M_PI*$sd))*pow(M_E, (-1*(pow(($val-$mean), 2)/(2*pow($sd, 2)))));

        return $d;
    }
    
    //(factors) يتم تمرير مصفوفة بيانات التدريب و الصفة ذات البيانات الرقمية المراد تقسيمها الى مجالات
    static public function factors($samples, $property)
    {
        $factors = [];
        $property_values = [];
        foreach ($samples as $index => $sample) {
            $property_values[] = $sample[$property];
        }
        sort($property_values);
        $ranges = array_chunk($property_values, ceil(count($property_values)/4));
        for ($i=0; $i < count($ranges); $i++) { 
            $factors[$i] = $ranges[$i][count($ranges[$i])-1];
        }

        return $factors;
    }

    static public function entropy($set)
    {
        return (-1*(($set['pos']/($set['pos']+$set['neg'])) * log(($set['pos']/($set['pos']+$set['neg']))))) - (($set['neg']/($set['neg']+$set['pos']))*log(($set['neg']/($set['neg']+$set['pos']))));
    }

    static public function gain($current_set, $all_child_set)
    {
        $current_set_entropy = ExpertTest::entropy($current_set);
        $all_child_sets_entropy = 0;
        foreach ($all_child_set as $index => $set) {
            $set_entropy = ExpertTest::entropy($set);
            $all_child_sets_entropy += ($set['pos']+$set['neg'])/($current_set['pos']+$current_set['neg']) * $set_entropy;
        }
        $gain = $current_set_entropy - $all_child_sets_entropy;
        return $gain;
    }

    public static function tableName()
    {
        return 'heart_disease_samples';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            //جميع القيم التالية مطلوب ادخالها من المستخدم
            [['age', 'chest_pain_type', 'rest_blood_pressure',
                'blood_sugar', 'rest_electro', 'max_heart_rate', 'exercice_angina'], 'required'],
            //جميع القيم التالية هي قيم رقمية
            [['age', 'rest_blood_pressure', 'max_heart_rate'], 'integer'],
            //جميع القيم التالية هي قيم نصية
            [['chest_pain_type', 'blood_sugar',
                'rest_electro', 'exercice_angina'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'age' => Yii::t('app', 'Age'),
            'chest_pain_type' => Yii::t('app', 'Chest Pain Type'),
            'rest_blood_pressure' => Yii::t('app', 'Rest Blood Pressure'),
            'blood_sugar' => Yii::t('app', 'Blood Sugar'),
            'rest_electro' => Yii::t('app', 'Rest Electro'),
            'max_heart_rate' => Yii::t('app', 'Max Heart Rate'),
            'exercice_angina' => Yii::t('app', 'Exercice Angina'),
            'disease' => Yii::t('app', 'Disease'),
        ];
    }
}

controllers/ExpertTestController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ExpertTest;
use app\models\ExpertTestSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;

/**
 * ExpertTestController implements the CRUD actions for ExpertTest model.
 */
class ExpertTestController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ExpertTest models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ExpertTestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ExpertTest model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ExpertTest model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ExpertTest();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ExpertTest model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ExpertTest model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ExpertTest model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ExpertTest the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ExpertTest::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function actionTest()
    {
        $model = new ExpertTest();
        if (Yii::$app->request->isPost) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $count_all = ExpertTest::find()->count();
            $count_pos = ExpertTest::find()->where(['disease' => 'positive'])->count();
            $count_neg = ExpertTest::find()->where(['disease' => 'negative'])->count();
            $ages = ExpertTest::find('age')->all();


            return [
                'count all' => $count_all,
                'count positive' => $count_pos,
                'count negative' => $count_neg,
                'ages' => $ages
            ];
        }

        return $this->render('test', [
            'model' => $model,
        ]);
    }

    public function actionBayesTest()
    {
        $model = new ExpertTest();

        if (Yii::$app->request->isPost)
        {
            //اسناد القيم المدخلة من قبل المسخدم الى متحولات
            $age = (int) Yii::$app->request->post()['ExpertTest']['age'];
            $chest_pain_type = Yii::$app->request->post()['ExpertTest']['chest_pain_type'];
            $rest_blood_pressure = (int) Yii::$app->request->post()['ExpertTest']['rest_blood_pressure'];
            $blood_sugar = Yii::$app->request->post()['ExpertTest']['blood_sugar'];
            $rest_electro = Yii::$app->request->post()['ExpertTest']['rest_electro'];
            $max_heart_rate = (int) Yii::$app->request->post()['ExpertTest']['max_heart_rate'];
            $exercice_angina = Yii::$app->request->post()['ExpertTest']['exercice_angina'];

            //مصفوفة تحوي جميع بيانات التدريب المخزنة بقاعدة البيانات
            $samples = ExpertTest::find()->all();
            
            //ايجاد عدد أمثلة التدريب
            $all_count = ExpertTest::find()->count();
            $pos_count = ExpertTest::find()->where(['disease' => 'positive'])->count();
            $neg_count = ExpertTest::find()->where(['disease' => 'negative'])->count();

            //ايجاد عدد أمثلة التدريب بالنسبة للبيانات النصية لكل من القيم الموجبة و السالبة
            $chest_pain_type_pos_count = ExpertTest::find()
                ->where(['disease' => 'positive'])
                ->andWhere(['chest_pain_type' => $chest_pain_type])
                ->count();
            $chest_pain_type_neg_count = ExpertTest::find()
                ->where(['disease' => 'negative'])
                ->andWhere(['chest_pain_type' => $chest_pain_type])
                ->count();

            $blood_sugar_pos_count = ExpertTest::find()
                ->where(['disease' => 'positive'])
                ->andWhere(['blood_sugar' => $blood_sugar])
                ->count();
            $blood_sugar_neg_count = ExpertTest::find()
                ->where(['disease' => 'negative'])
                ->andWhere(['blood_sugar' => $blood_sugar])
                ->count();

            $rest_electro_pos_count = ExpertTest::find()
                ->where(['disease' => 'positive'])
                ->andWhere(['rest_electro' => $rest_electro])
                ->count();
            $rest_electro_neg_count = ExpertTest::find()
                ->where(['disease' => 'negative'])
                ->andWhere(['rest_electro' => $rest_electro])
                ->count();

            $exercice_angina_pos_count = ExpertTest::find()
                ->where(['disease' => 'positive'])
                ->andWhere(['exercice_angina' => $exercice_angina])
                ->count();
            $exercice_angina_neg_count = ExpertTest::find()
                ->where(['disease' => 'negative'])
                ->andWhere(['exercice_angina' => $exercice_angina])
                ->count();

            $age_pos = [];
            $age_neg = [];
            
            $rest_blood_pressure_pos = [];
            $rest_blood_pressure_neg = [];
            
            
            $max_heart_rate_pos = [];
            $max_heart_rate_neg = [];

            //ايجاد عدد أمثلة التدريب بالنسبة للبيانات العددية لكل من القيم الموجبة و السالبة
            foreach ($samples as $sample) {
                if($sample->disease == 'positive')
                {
                    $age_pos[] = $sample->age;
                    $rest_blood_pressure_pos[] = $sample->rest_blood_pressure;
                    $max_heart_rate_pos[] = $sample->max_heart_rate;
                }
                else {
                    $age_neg[] = $sample->age;
                    $rest_blood_pressure_neg[] = $sample->rest_blood_pressure;
                    $max_heart_rate_neg[] = $sample->max_heart_rate;
                }
            }
            //حساب الكثافة من أجل القيم العددية
            $age_pos_dens = ExpertTest::density($age_pos, $age);
            $age_neg_dens = ExpertTest::density($age_neg, $age);
    
            $rest_blood_pressure_pos_dens = ExpertTest::density($rest_blood_pressure_pos,
                $rest_blood_pressure);
            $rest_blood_pressure_neg_dens = ExpertTest::density($rest_blood_pressure_neg,
                $rest_blood_pressure);
    
            $max_heart_rate_pos_dens = ExpertTest::density($max_heart_rate_pos, $max_heart_rate);
            $max_heart_rate_neg_dens = ExpertTest::density($max_heart_rate_neg , $max_heart_rate);
            
            //bayesايجاد احتمال كل من الموجب و السالب حسب معادلة
            $probability_pos = ($age_pos_dens) *
                                ($chest_pain_type_pos_count / $pos_count) *
                                ($rest_blood_pressure_pos_dens) *
                                ($blood_sugar_pos_count / $pos_count) * 
                                ($rest_electro_pos_count / $pos_count) * 
                                ($max_heart_rate_pos_dens) * 
                                ($exercice_angina_pos_count / $pos_count) * 
                                ($pos_count / $all_count);

            $probability_neg = ($age_neg_dens) * 
                                ($chest_pain_type_neg_count / $neg_count) * 
                                ($rest_blood_pressure_neg_dens) * 
                                ($blood_sugar_neg_count / $neg_count) * 
                                ($rest_electro_neg_count / $neg_count) * 
                                ($max_heart_rate_neg_dens) * 
                                ($exercice_angina_neg_count / $neg_count) * 
                                ($neg_count / $all_count);

            $positive_result = (float) (($probability_pos / ($probability_pos + $probability_neg)) * 100);
            $negative_result = (float) (($probability_neg / ($probability_neg + $probability_pos)) * 100);

views/expert-test/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ExpertTest */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="expert-test-form _form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'age')->textInput(['type' => 'number', 'min' => 18, 'max' => 110]) ?>

    <?= $form->field($model, 'chest_pain_type')->dropDownList([ 'asympt' => 'Asympt', 'atyp_angina' => 'Atyp angina', 'non_anginal' => 'Non anginal', 'typ_angina' => 'Typ angina', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'rest_blood_pressure')->textInput(['type' => 'number', 'min' => 60, 'max' => 250]) ?>

    <?= $form->field($model, 'blood_sugar')->dropDownList([ 'TRUE' => 'TRUE', 'FALSE' => 'FALSE', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'rest_electro')->dropDownList([ 'normal' => 'Normal', 'left_vent_hyper' => 'Left vent hyper', 'st_t_wave_abnormality' => 'St t wave abnormality', 'not_set' => 'Not set', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'max_heart_rate')->textInput(['type' => 'number', 'min' => 60, 'max' => 250]) ?>

    <?= $form->field($model, 'exercice_angina')->dropDownList([ 'yes' => 'Yes', 'no' => 'No', ], ['prompt' => '']) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Send'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/expert-test/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ExpertTestSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="expert-test-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'age') ?>

    <?= $form->field($model, 'chest_pain_type') ?>

    <?= $form->field($model, 'rest_blood_pressure') ?>

    <?= $form->field($model, 'blood_sugar') ?>

    <?php // echo $form->field($model, 'rest_electro') ?>

    <?php // echo $form->field($model, 'max_heart_rate') ?>

    <?php // echo $form->field($model, 'exercice_angina') ?>

    <?php // echo $form->field($model, 'disease') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/expert-test/bayes-result.php
<?php

use yii\helpers\Html;

?>

<div>
    <h1>Result:</h1>
    <h3>Your result according to Naive Bayes Algorithm is:</h3>
    <h3>Positive: <?= $positive ?>% and Negative: <?= $negative ?>%</h3> 
    <br>
    <h2>Your test result is: <?= ($result == 'Positive' ? "<span style='color:red'>" . $result. "</span>" : "<span style='color:green'>" . $result. "</span>");$result ?></h2>
    <?= Html::a(Yii::t('app', 'Redo Test'), ['expert-test/bayes-test'], ['class' => 'btn btn-primary']) ?>
</div>

views/expert-test/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ExpertTest */

$this->title = Yii::t('app', 'Create Expert Test');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Expert Tests'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="expert-test-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/expert-test/expert-test.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Expert Heart Test');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="expert-test-create">

<h1><?= Html::encode($this->title) ?></h1>
<h3>Please fill in the following information to perform an online expert heart test:</h3>
<hr>

<div class="expert-test-form _form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'age')->textInput(['type' => 'number', 'min' => 18, 'max' => 110]) ?>

    <?= $form->field($model, 'chest_pain_type')->dropDownList([
        'asympt' => 'Asympt',
        'atyp_angina' => 'Atyp angina',
        'non_anginal' => 'Non anginal',
        'typ_angina' => 'Typ angina', 
        ],
        ['prompt' => ''])
    ?>

    <?= $form->field($model, 'rest_blood_pressure')->textInput([
        'type' => 'number', 'min' => 60, 'max' => 250
        ]) ?>

    <?= $form->field($model, 'blood_sugar')->dropDownList([
        'TRUE' => 'TRUE', 'FALSE' => 'FALSE', 
        ],
        ['prompt' => '']) ?>

    <?= $form->field($model, 'rest_electro')->dropDownList([
        'normal' => 'Normal',
        'left_vent_hyper' => 'Left vent hyper',
        'st_t_wave_abnormality' => 'St t wave abnormality'
        ], 
        ['prompt' => '']) ?>

    <?= $form->field($model, 'max_heart_rate')->textInput([
        'type' => 'number', 'min' => 60, 'max' => 250
        ]) ?>

    <?= $form->field($model, 'exercice_angina')->dropDownList([
        'yes' => 'Yes', 'no' => 'No'
        ],
        ['prompt' => '']) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Send'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

</div>

views/expert-test/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ExpertTestSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Expert Tests');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="expert-test-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create Expert Test'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'age',
            'chest_pain_type',
            'rest_blood_pressure',
            'blood_sugar',
            //'rest_electro',
            //'max_heart_rate',
            //'exercice_angina',
            //'disease',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/expert-test/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ExpertTest */

$this->title = Yii::t('app', 'Update Expert Test: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Expert Tests'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="expert-test-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/expert-test/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ExpertTest */

$this->title = $model->id;
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="expert-test-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'age',
            'chest_pain_type',
            'rest_blood_pressure',
            'blood_sugar',
            'rest_electro',
            'max_heart_rate',
            'exercice_angina',
            'disease',
        ],
    ]) ?>

</div>